---
# tasks file for docker-registry
- name: Tag image
  become: yes
  shell: docker tag myapp-cd yassinebenamor/projet-cd:latest

- name: Login to Dockerhub
  become: yes
  shell: docker login --username yassinebenamor --password dckr_pat_v0uNtlHTwEFTcCsA7p5s91lBXhI
  
- name: Push image to DockerHub 
  become: yes
  shell: docker push yassinebenamor/projet-cd:latest
