---
# tasks file for docker-registry
- name: Tag image
  become: yes
  shell: docker tag yassinebenamor/myapp-cd yassinebenamor/projet-cd:latest
  
- name: Push image to DockerHub 
  become: yes
  shell: docker push yassinebenamor/projet-cd:latest
